--select * from CUSTOMERS where CUSTOMERNAME like 'a%' and GENDER='e'



--select * from CUSTOMERS where BIRTHDATE BETWEEN '1990-01-01' AND '1995-12-31'
--SELECT * FROM CUSTOMERS WHERE YEAR(BIRTHDATE) BETWEEN 1990 AND 1995 



--SELECT CUS.*,CIT.CITY FROM CUSTOMERS CUS
--INNER JOIN CITIES CIT ON CIT.ID=CUS.CITYID
--WHERE CITY='ÝSTANBUL'



--SELECT * FROM CUSTOMERS WHERE CITYID=(SELECT ID FROM CITIES WHERE CITY='ÝSTANBUL')


--SELECT 
--(SELECT CITY FROM CITIES WHERE ID=CUSTOMERS.CITYID),*
--FROM CUSTOMERS
--WHERE CUSTOMERS.CITYID IN
--(SELECT ID FROM CITIES WHERE CITY IN ('ÝSTANBUL','ANKARA'))





--SELECT COUNT(CITY) AS KÝSÝ_SAYÝSÝ,CITY  FROM CUSTOMERS CUS
--INNER JOIN CITIES CIT ON CIT.ID=CUS.CITYID  --RIGHT DA KULLANILIR
--GROUP BY CITY


--SELECT 
--*,(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID) KÝSÝSAYÝSÝ
--FROM CITIES C
--ORDER BY 3 --ID CITY KÝSÝSAYÝSÝ- ÜÇ SÜTUN

 
--select CT.CITY,COUNT(C.ID) AS CUSTOMERCOUNT from CUSTOMERS C
--INNER JOIN CITIES CT  ON C.CITYID=CT.ID
--GROUP BY CT.CITY 
--HAVING COUNT(C.ID)>10 
--ORDER BY CUSTOMERCOUNT DESC


--SELECT *,(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID) FROM CITIES C
--WHERE
--(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID)>10
--ORDER BY 3 DESC


--SELECT CT.CITY,C.GENDER,COUNT(C.ID) FROM CUSTOMERS C
--INNER JOIN CITIES CT ON CT.ID=C.CITYID
--GROUP BY CT.CITY,C.GENDER
--ORDER BY 1,2

--SELECT CITY AS SEHIRADI,
--(SELECT COUNT(*) FROM CUSTOMERS C WHERE C.CITYID=CT.ID ) AS MSUTERISAYISI,
--(SELECT COUNT(*) FROM CUSTOMERS C WHERE C.CITYID=CT.ID AND GENDER='E') AS ERKEK,
--(SELECT COUNT(*) FROM CUSTOMERS C WHERE C.CITYID=CT.ID AND GENDER='K') AS KADIN
--FROM CITIES CT


--SELECT 
--*,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS YAÞ
-- FROM CUSTOMERS 

--UPDATE CUSTOMERS SET AGEGROUP = '20-35 YAS' WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35

--UPDATE CUSTOMERS SET AGEGROUP = '36-45 YAS' WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45

--UPDATE CUSTOMERS SET AGEGROUP = '46-55 YAS' WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55

--UPDATE CUSTOMERS SET AGEGROUP = '55-65 YAS' WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65

--UPDATE CUSTOMERS SET AGEGROUP = '65 ÜSTÜ' WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE())>65


--17--
--SELECT

--CASE
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE())>65 THEN '65 ÜSTÜ'
--END YASGRUBU,
--COUNT(*) AS MUSTERÝSAYISI

--FROM CUSTOMERS

--GROUP BY
--CASE
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE())>65 THEN '65 ÜSTÜ'
--END

--ORDER BY 1
----------------------------------------------------------------------------------------
--SELECT YASGRUBU2,COUNT(TMP.ID) AS MUSTERÝSAYISI2 FROM
--(
--SELECT *,
--CASE
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAS'
--	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE())>65 THEN '65 ÜSTÜ'
--END YASGRUBU2


--FROM CUSTOMERS
--) TMP
--GROUP BY YASGRUBU2
--ORDER BY 1
--------------------------------------
--18

--SELECT C.CUSTOMERNAME,CT.CITY,D.DISTRICT FROM CUSTOMERS C
--INNER JOIN CITIES CT ON CT.ID=C.CITYID
--INNER JOIN DISTRICTS D ON D.ID=C.DISTRICTID
--WHERE CITY='ÝSTANBUL' AND DISTRICT != 'KADIKÖY'
---------------------------------------------------------------
--19

--SELECT * FROM CUSTOMERS C
--LEFT JOIN CITIES CT ON CT.ID=C.CITYID
--WHERE CT.CITY IS NULL
-------------------------------------
--20
--SET IDENTITY_INSERT CITIES ON   --- ARADAN SÝLÝNEN KAYDI TEKRAR KOYMAK ÝÇÝN

--INSERT INTO CITIES(ID,CITY)
--VALUES (34,'ÝSTANBUL')

--------------------------------------------------------
--21
--SELECT C.CUSTOMERNAME,
--SUBSTRING(TELNR1,2,3) AS OPERATOR1,
--SUBSTRING(TELNR2,0,6) AS OPERATOR2 
--FROM CUSTOMERS C
----------------------------------------------------------
--22

--SELECT 
--CASE
--	WHEN SUBSTRING(TELNR1,2,2) = 50  THEN 'XOPERATORU' 
--	WHEN SUBSTRING(TELNR1,2,2) = 55  THEN 'XOPERATORU'
--	WHEN SUBSTRING(TELNR1,2,2) = 54  THEN 'YOPERATORU'
--	WHEN SUBSTRING(TELNR1,2,2) = 53  THEN 'ZOPERATORU'
--	WHEN SUBSTRING(TELNR2,2,2) = 50  THEN 'XOPERATORU' 
--	WHEN SUBSTRING(TELNR2,2,2) = 55  THEN 'XOPERATORU'
--	WHEN SUBSTRING(TELNR2,2,2) = 54  THEN 'YOPERATORU'
--	WHEN SUBSTRING(TELNR2,2,2) = 53  THEN 'ZOPERATORU'
--END OPERATOR,
--COUNT(*) AS KÝSÝSAYÝSÝ

--FROM CUSTOMERS
--GROUP BY
--CASE
--	WHEN SUBSTRING(TELNR1,2,2) =50  THEN 'XOPERATORU'
--	WHEN SUBSTRING(TELNR1,2,2) =55  THEN 'XOPERATORU'
--	WHEN SUBSTRING(TELNR1,2,2) =54  THEN 'YOPERATORU'
--	WHEN SUBSTRING(TELNR1,2,2) =53  THEN 'ZOPERATORU'
--	WHEN SUBSTRING(TELNR2,2,2) = 50  THEN 'XOPERATORU' 
--	WHEN SUBSTRING(TELNR2,2,2) = 55  THEN 'XOPERATORU'
--	WHEN SUBSTRING(TELNR2,2,2) = 54  THEN 'YOPERATORU'
--	WHEN SUBSTRING(TELNR2,2,2) = 53  THEN 'ZOPERATORU'
--END

----------------------------------------
--23

--SELECT CT.CITY,D.DISTRICT,COUNT(C.ID) FROM CUSTOMERS C
--INNER JOIN CITIES CT ON CT.ID=C.CITYID
--INNER JOIN DISTRICTS D ON D.ID=C.DISTRICTID
--GROUP BY CT.CITY,D.DISTRICT
--ORDER BY 1,COUNT(C.ID)DESC
-----------------------------------------
--24


--SELECT C.CUSTOMERNAME,DATENAME(DW,BIRTHDATE),
--CASE 
--	WHEN DATENAME(DW,BIRTHDATE)='Monday' THEN 'PAZARTESÝ'
--	WHEN DATENAME(DW,BIRTHDATE)='Tuesday ' THEN 'SALI'
--	WHEN DATENAME(DW,BIRTHDATE)='Wednesday ' THEN 'ÇARÞAMBA'
--	WHEN DATENAME(DW,BIRTHDATE)='Thursday  ' THEN 'PERÞEMBE'
--	WHEN DATENAME(DW,BIRTHDATE)='Friday  ' THEN 'CUMA'
--	WHEN DATENAME(DW,BIRTHDATE)='Saturday   ' THEN 'CUMARTESÝ'
--	WHEN DATENAME(DW,BIRTHDATE)='Sunday  ' THEN 'PAZAR'

--END

--FROM CUSTOMERS C
---------------------------------------------
----24
--SET LANGUAGE Turkish
--SELECT C.CUSTOMERNAME,DATENAME(DW,BIRTHDATE)


--FROM CUSTOMERS C
-------------------------------------
--25
--SELECT * FROM CUSTOMERS WHERE DATEPART(MONTH,BIRTHDATE)=5 AND  DATEPART(DAY,BIRTHDATE)=5

--DATEPART(MONTH,GETDATE())
--DATEPART(MONTH,GETDATE())